language: cpp
compiler: gcc
sudo: required
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x 
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get purge cmake
  - sudo apt-get install -yq build-essential gcc-4.8 g++-4.8 gcc-4.8-multilib g++-4.8-multilib
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - echo 2 | sudo update-alternatives --config gcc
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.3.0-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.3.0-Linux-x86_64/* /usr
  - rm -rf cmake-3.3.0-Linux-x86_64
  - rm cmake-3.3.0-Linux-x86_64.tar.gz
  - g++ --version
  - cmake --version
script:
  - cmake -G "Unix Makefiles"
  - make
